export const PRODUCTS_GET = 'PRODUCTS_GET';
export const PRODUCTS_GET__SUCCESS = 'PRODUCTS_GET__SUCCESS';
export const PRODUCTS_GET__FAIL = 'PRODUCTS_GET__FAIL';

export const CATEGORIES_GET = 'CATEGORIES_GET';
export const CATEGORIES_GET__SUCCESS = 'CATEGORIES_GET__SUCCESS';
export const CATEGORIES_GET__FAIL = 'CATEGORIES_GET__FAIL';

export const EXCHANGE_RATES_GET = 'EXCHANGE_RATES_GET';

export const BASKET_PRODUCT_ADD = 'BASKET_PRODUCT_ADD';
export const BASKET_PRODUCT_REMOVE = 'BASKET_PRODUCT_REMOVE';
export const QUANTITY_SET = 'QUANTITY_SET';
